/* ─── FIGHTERS ──────────────────────────────────────────── */
window.FIGHTERS = [
  // Items
  {id:1,name:"100 Rubber Ducks",tag:"squeaky and unstoppable",cat:"items"},
  {id:2,name:"A Roomba",tag:"tireless floor guardian",cat:"items"},
  {id:3,name:"A Pool Noodle",tag:"floats above the competition",cat:"items"},
  {id:4,name:"A Microwave",tag:"beeps with authority",cat:"items"},
  {id:5,name:"An Entire Costco",tag:"bulk power, baby",cat:"items"},
  {id:6,name:"A Shopping Cart",tag:"rolling chaos energy",cat:"items"},
  {id:7,name:"A 2001 Honda Civic",tag:"still running somehow",cat:"items"},
  {id:8,name:"A Fidget Spinner",tag:"peak 2017 energy",cat:"items"},
  {id:9,name:"A Dyson Vacuum",tag:"sucks at losing",cat:"items"},
  {id:10,name:"A Slightly Damp Sock",tag:"uncomfortably determined",cat:"items"},
  {id:11,name:"The Last Slice of Pizza",tag:"worth fighting for",cat:"items"},
  {id:12,name:"A Vending Machine",tag:"refuses to give up OR give change",cat:"items"},
  {id:13,name:"A Broken Umbrella",tag:"still showing up",cat:"items"},
  {id:14,name:"A Very Sharp Pencil",tag:"pointedly dangerous",cat:"items"},
  // Animals
  {id:15,name:"1 Horse",tag:"neigh means yes, I win",cat:"animals"},
  {id:16,name:"A Golden Retriever",tag:"good boy energy is unstoppable",cat:"animals"},
  {id:17,name:"100 Squirrels",tag:"chaotic nut energy",cat:"animals"},
  {id:18,name:"A Honey Badger",tag:"don't care, won't care",cat:"animals"},
  {id:19,name:"A Murder of Crows",tag:"plotting since dawn",cat:"animals"},
  {id:20,name:"A Capybara",tag:"terrifyingly chill",cat:"animals"},
  {id:21,name:"A Swarm of Bees",tag:"democracy in action",cat:"animals"},
  {id:22,name:"A Florida Man",tag:"headlines write themselves",cat:"animals"},
  {id:23,name:"A Single Goose",tag:"no mercy, no remorse",cat:"animals"},
  {id:24,name:"A Raccoon With Nothing to Lose",tag:"trash panda champion",cat:"animals"},
  {id:25,name:"50 Ferrets in a Trenchcoat",tag:"organized chaos",cat:"animals"},
  {id:26,name:"A Golden Retriever with a PhD",tag:"academically good boy",cat:"animals"},
  {id:27,name:"A Sleepy Sloth",tag:"eventually gets there",cat:"animals"},
  {id:28,name:"A Grizzly Bear",tag:"doesn't negotiate",cat:"animals"},
  // Pop Culture
  {id:29,name:"SpongeBob SquarePants",tag:"I'm ready!",cat:"popculture"},
  {id:30,name:"Shrek",tag:"this is my swamp, I win",cat:"popculture"},
  {id:31,name:"The Mandalorian",tag:"this is the way",cat:"popculture"},
  {id:32,name:"John Wick",tag:"breathes pure revenge",cat:"popculture"},
  {id:33,name:"Baby Yoda (Grogu)",tag:"force is strong with this snack",cat:"popculture"},
  {id:34,name:"Walter White",tag:"I am the one who wins",cat:"popculture"},
  {id:35,name:"Tony Stark",tag:"genius. billionaire. winner.",cat:"popculture"},
  {id:36,name:"Gollum",tag:"my precious... victory",cat:"popculture"},
  {id:37,name:"Darth Vader",tag:"heavy breathing into trophies",cat:"popculture"},
  {id:38,name:"Thanos",tag:"perfectly balanced, as all wins should be",cat:"popculture"},
  {id:39,name:"The Terminator",tag:"I'll be back... with the W",cat:"popculture"},
  {id:40,name:"Captain Jack Sparrow",tag:"savvy?",cat:"popculture"},
  {id:41,name:"Gandalf",tag:"you shall not LOSE",cat:"popculture"},
  {id:42,name:"Hermione Granger",tag:"technically always right",cat:"popculture"},
  {id:43,name:"Michael Scott",tag:"that's what she said... I win",cat:"popculture"},
  {id:44,name:"Ron Swanson",tag:"government-hating champion",cat:"popculture"},
  {id:45,name:"Dwight Schrute",tag:"assistant TO the winner",cat:"popculture"},
  {id:46,name:"The Joker",tag:"why so serious about losing?",cat:"popculture"},
  {id:47,name:"Deadpool",tag:"fourth wall? more like fourth WIN",cat:"popculture"},
  {id:48,name:"Mario",tag:"it'sa me, the winner!",cat:"popculture"},
  {id:49,name:"Sonic the Hedgehog",tag:"gotta go fast to victory",cat:"popculture"},
  {id:50,name:"Pikachu",tag:"I choose YOU to lose",cat:"popculture"},
  {id:51,name:"Donkey Kong",tag:"banana-powered greatness",cat:"popculture"},
  {id:52,name:"Link (from Zelda)",tag:"silent but absolutely deadly",cat:"popculture"},
  {id:53,name:"Patrick Star",tag:"is mayonnaise a strategy?",cat:"popculture"},
  {id:54,name:"Squidward",tag:"artistically superior at everything",cat:"popculture"},
  {id:55,name:"Homer Simpson",tag:"mmm... winning",cat:"popculture"},
  {id:56,name:"Bart Simpson",tag:"don't have a cow, man",cat:"popculture"},
  {id:57,name:"Peter Griffin",tag:"this reminds me of the time I won...",cat:"popculture"},
  {id:58,name:"Stewie Griffin",tag:"blast! still winning.",cat:"popculture"},
  {id:59,name:"Rick Sanchez",tag:"wubba lubba dub dub, I win",cat:"popculture"},
  {id:60,name:"The Incredible Hulk",tag:"Hulk SMASH competition",cat:"popculture"},
  {id:61,name:"Spider-Man",tag:"with great power comes great W's",cat:"popculture"},
  {id:62,name:"Batman",tag:"I'm Batman. I win.",cat:"popculture"},
  {id:63,name:"Wednesday Addams",tag:"joylessly dominant in all things",cat:"popculture"},
  {id:64,name:"Shaggy (at full power)",tag:"using 0.01% of his strength",cat:"popculture"},
  {id:65,name:"Gru (from Despicable Me)",tag:"has a plan. an elaborate plan.",cat:"popculture"},
  {id:66,name:"The Mandela Effect",tag:"wins in every alternate timeline",cat:"popculture"},
  // Celebs
  {id:67,name:"Gordon Ramsay",tag:"this victory is RAW",cat:"celebs"},
  {id:68,name:"Dwayne Johnson",tag:"can you smell what The Rock is winning?",cat:"celebs"},
  {id:69,name:"Oprah",tag:"YOU get a win! YOU get a win!",cat:"celebs"},
  {id:70,name:"Bob Ross",tag:"happy little victories",cat:"celebs"},
  {id:71,name:"Mr. T",tag:"I pity the fool who loses to me",cat:"celebs"},
  {id:72,name:"Chuck Norris",tag:"Chuck doesn't compete. He just wins.",cat:"celebs"},
  {id:73,name:"Nicolas Cage",tag:"NOT THE BEES... but still winning",cat:"celebs"},
  {id:74,name:"Keanu Reeves",tag:"breathtaking victory",cat:"celebs"},
  {id:75,name:"Danny DeVito",tag:"surprisingly and terrifyingly good",cat:"celebs"},
  {id:76,name:"Morgan Freeman (narrating)",tag:"and then... they won",cat:"celebs"},
  {id:77,name:"Betty White's Ghost",tag:"still the most powerful being",cat:"celebs"},
  {id:78,name:"David Attenborough",tag:"narrating victory into existence",cat:"celebs"},
  {id:79,name:"Gordon Ramsay's Ego",tag:"a separate, larger entity",cat:"celebs"},
  // Memes
  {id:80,name:"The Doge",tag:"very win. much champion. wow.",cat:"memes"},
  {id:81,name:"Grumpy Cat",tag:"already lost. doesn't care.",cat:"memes"},
  {id:82,name:"Harambe's Ghost",tag:"still an icon. still powerful.",cat:"memes"},
  {id:83,name:"This Is Fine Dog",tag:"winning while everything burns",cat:"memes"},
  {id:84,name:"Big Chungus",tag:"chonky and absolutely unstoppable",cat:"memes"},
  {id:85,name:"Nyan Cat",tag:"leaving rainbows of victory",cat:"memes"},
  {id:86,name:"Salt Bae",tag:"seasoning the competition",cat:"memes"},
  {id:87,name:"1000 Pigeons in a Trenchcoat",tag:"definitely a human. definitely winning.",cat:"memes"},
  {id:88,name:"Area 51 Naruto Runner",tag:"they can't stop all of us",cat:"memes"},
  {id:89,name:"The Confused Math Lady",tag:"calculating exactly how to win",cat:"memes"},
  {id:90,name:"'To Be Continued' Arrow",tag:"victory is inevitable",cat:"memes"},
  {id:91,name:"Wojak",tag:"painfully relatable winner",cat:"memes"},
  // Roles
  {id:92,name:"A Kindergarten Teacher",tag:"survived worse, will survive this",cat:"roles"},
  {id:93,name:"A Divorced Dad",tag:"just bought a sports car and a grill",cat:"roles"},
  {id:94,name:"A Karen",tag:"wants to speak to the referee",cat:"roles"},
  {id:95,name:"An Overworked Barista",tag:"has seen dark things. dark things.",cat:"roles"},
  {id:96,name:"A Tired Nurse",tag:"no days off. no losses.",cat:"roles"},
  {id:97,name:"A Mall Santa",tag:"knows who's been naughty",cat:"roles"},
  {id:98,name:"A DMV Employee",tag:"outlasted everyone, will outlast you",cat:"roles"},
  {id:99,name:"The Guitar Guy at Parties",tag:"Wonderwall your way to victory",cat:"roles"},
  {id:100,name:"A Philosophy Major",tag:"but what even IS winning?",cat:"roles"},
  {id:101,name:"A Retired Ninja",tag:"semi-retired. still absolutely deadly.",cat:"roles"},
  {id:102,name:"50 Kindergarteners",tag:"utter chaos. maximum energy.",cat:"roles"},
  {id:103,name:"A Toddler with Scissors",tag:"certified certified menace",cat:"roles"},
  {id:104,name:"An Immortal Grandmother",tag:"seen it all. still going.",cat:"roles"},
  {id:105,name:"The Entire Cast of Mamma Mia",tag:"ABBA-solutely dominant",cat:"roles"},
  {id:106,name:"A LinkedIn Influencer",tag:"turning this loss into thought leadership",cat:"roles"},
  {id:107,name:"A World's Most Patient Librarian",tag:"quiet strength, loud results",cat:"roles"},
  // Abstract
  {id:108,name:"Time Itself",tag:"always wins eventually",cat:"abstract"},
  {id:109,name:"The Economy",tag:"crashing its way to first place",cat:"abstract"},
  {id:110,name:"Gravity",tag:"inevitable. like my victory.",cat:"abstract"},
  {id:111,name:"A 6-Year-Old Who Just Learned About Dinosaurs",tag:"ACTUALLY THEY COULD FLY",cat:"abstract"},
  {id:112,name:"An AI Chatbot",tag:"just here to assist your defeat",cat:"abstract"},
  {id:113,name:"The Concept of Mondays",tag:"ruins everything, always wins",cat:"abstract"},
  {id:114,name:"The Algorithm",tag:"knows what you want before you do",cat:"abstract"},
  {id:115,name:"The Last 2% of Your Phone Battery",tag:"absolute psychological terror",cat:"abstract"},
  {id:116,name:"A Brutal Case of Writer's Block",tag:"staring at a blank page forever",cat:"abstract"},
  {id:117,name:"The Existential Dread of a Perfectly Restocked Retail Aisle",tag:"everything is where it belongs, but at what cost?",cat:"abstract"},
  {id:118,name:"A 99-Day Digital Streak",tag:"pure, unadulterated, sleep-deprived commitment",cat:"abstract"},
  {id:119,name:"A mid 2000s Pop Punk Song Title",tag:"misunderstood but incredibly loud",cat:"abstract"},
  {id:120,name:"An Unpolished Fluorite Crystal",tag:"natural, bespoke, and hard as rock",cat:"abstract"},
  {id:121,name:"The Sunk Cost Fallacy",tag:"you're already this far in, might as well win",cat:"abstract"},
  {id:122,name:"Dodger Stadium Traffic",tag:"an inescapable, soul-crushing force",cat:"abstract"},
  {id:123,name:"Unearned Confidence",tag:"doesn't know what's happening, still winning",cat:"abstract"},
  {id:124,name:"A Really Good Iced Coffee",tag:"the only thing holding it all together",cat:"abstract"},
  {id:125,name:"The Concept of 'Maybe Later'",tag:"undefeated champion of procrastination",cat:"abstract"},
];

/* ─── EXPANSION PACKS ────────────────────────────────────── */
window.EXPANSION_PACKS = [
  {
    id: "pack_history",
    name: "HISTORY'S WEIRDEST",
    emoji: "🏛️",
    description: "Ancient rulers, famous failures & historical wildcards. Time travel sold separately.",
    fighters: [
      {id:2001,name:"Genghis Khan on a Monday",tag:"conquered empires before breakfast",cat:"history"},
      {id:2002,name:"Cleopatra's PR Team",tag:"aggressively spinning the narrative",cat:"history"},
      {id:2003,name:"A Viking Who Just Discovered Coffee",tag:"already dangerous. now caffeinated.",cat:"history"},
      {id:2004,name:"Napoleon's Height Debate",tag:"surprisingly not the issue here",cat:"history"},
      {id:2005,name:"Sun Tzu, But For Trivia Night",tag:"all warfare is based on deception",cat:"history"},
      {id:2006,name:"A Victorian Ghost Hunter",tag:"100% certain, 0% accurate",cat:"history"},
      {id:2007,name:"An Egyptian Pharaoh with a Yelp Account",tag:"3 stars. pyramid was drafty.",cat:"history"},
      {id:2008,name:"Julius Caesar's Last Text Draft",tag:"et tu, autocorrect?",cat:"history"},
      {id:2009,name:"A Plague Doctor with Social Anxiety",tag:"the mask is for health reasons. definitely.",cat:"history"},
      {id:2010,name:"The Loch Ness Monster's Publicist",tag:"managing impossible expectations since 1933",cat:"history"},
      {id:2011,name:"A Spartan Who Does Yoga Now",tag:"come back with your shield or on it... but also namaste",cat:"history"},
      {id:2012,name:"Marie Curie's Glow",tag:"radioactively unstoppable",cat:"history"},
    ],
    scenarios: [
      "a medieval jousting tournament on Segways",
      "writing a Yelp review for the Colosseum",
      "speed-running the construction of the Great Wall",
      "explaining the internet to Aristotle",
      "hosting a Renaissance Fair on a cruise ship",
      "a chariot race through downtown LA",
      "negotiating a peace treaty using only emojis",
      "planning Cleopatra's bachelorette party",
    ]
  },
  {
    id: "pack_sports",
    name: "ATHLETIC CHAOS",
    emoji: "🏆",
    description: "Sports legends, cursed athletes & the ultimate battle of who actually has game.",
    fighters: [
      {id:3001,name:"A Youth Soccer Coach in Overtime",tag:"THIS IS NOT A DRILL, KYLE",cat:"sports"},
      {id:3002,name:"An Olympian Who Peaked in 2008",tag:"technically still medaled",cat:"sports"},
      {id:3003,name:"A Little League Parent",tag:"would like to speak to the umpire",cat:"sports"},
      {id:3004,name:"A Cornhole Champion",tag:"don't underestimate the bags",cat:"sports"},
      {id:3005,name:"The Entire 1992 Dream Team",tag:"just absolutely overkill",cat:"sports"},
      {id:3006,name:"A Horse That Only Runs for Snacks",tag:"motivated. selectively.",cat:"sports"},
      {id:3007,name:"A Competitive Eater in Pre-Game Mode",tag:"jaw is warmed up. eyes are locked.",cat:"sports"},
      {id:3008,name:"A Professional Disc Golfer",tag:"dismissed by society. elite in the woods.",cat:"sports"},
      {id:3009,name:"A Bobsled Team from Jamaica",tag:"cool runnings energy, maximum heart",cat:"sports"},
      {id:3010,name:"A Marathon Runner at Mile 22",tag:"dead inside. legs still going.",cat:"sports"},
      {id:3011,name:"An E-Sports Pro on LAN",tag:"ping 4ms. zero social skills. pure focus.",cat:"sports"},
      {id:3012,name:"A Retired Wrestler with One More Match",tag:"the music just hit. it's over for you.",cat:"sports"},
    ],
    scenarios: [
      "a backyard Wiffle Ball world series",
      "a three-legged race at the Olympics",
      "a bowling tournament with 10-second shot clocks",
      "an all-or-nothing free throw for the championship",
      "a 5K run where the course is entirely uphill",
      "a sudden-death mini golf face-off",
      "a fantasy sports draft with real people as prizes",
      "a competitive hot dog eating qualifier round",
    ]
  },
  {
    id: "pack_holiday",
    name: "HOLIDAY CHAOS",
    emoji: "🎄",
    description: "Santa's enemies, cursed traditions & the most unhinged seasonal showdowns.",
    fighters: [
      {id:4001,name:"A Christmas Tree That's Given Up",tag:"shedding needles but still standing",cat:"holiday"},
      {id:4002,name:"A Black Friday Shopper at 4am",tag:"sleep-deprived and fully committed",cat:"holiday"},
      {id:4003,name:"The Ghost of New Year's Past",tag:"still mad about 2012",cat:"holiday"},
      {id:4004,name:"A Passive-Aggressive Secret Santa",tag:"$20 limit. chaos delivered.",cat:"holiday"},
      {id:4005,name:"An Elf on the Shelf Gone Rogue",tag:"has seen too much. tells no one.",cat:"holiday"},
      {id:4006,name:"Halloween 2020",tag:"the most unhinged year in costume",cat:"holiday"},
      {id:4007,name:"A Defective Firework",tag:"unpredictable. dangerous. July.",cat:"holiday"},
      {id:4008,name:"A Thanksgiving Turkey That Escaped",tag:"motivated by survival. running on instinct.",cat:"holiday"},
      {id:4009,name:"The One Relative Who Brings Up Politics",tag:"100% going to do it. cannot be stopped.",cat:"holiday"},
      {id:4010,name:"A Menorah in a Power Outage",tag:"8 nights. zero excuses.",cat:"holiday"},
      {id:4011,name:"A Valentine's Day Candy Heart That Says 'WHATEVER'",tag:"said it before it was cool",cat:"holiday"},
      {id:4012,name:"St. Patrick's Day at 11pm",tag:"questionable. unstoppable. still going.",cat:"holiday"},
    ],
    scenarios: [
      "a gingerbread house construction competition with no instructions",
      "a mall on December 23rd",
      "explaining your New Year's resolutions to your past self",
      "surviving a family road trip with no phone service",
      "a costume contest where everyone came as the same thing",
      "caroling for a crowd that specifically requested no caroling",
      "hosting Thanksgiving with a 2-hour notice",
      "a white elephant gift exchange that has escalated beyond reason",
    ]
  },
  {
    id: "pack_food",
    name: "FOOD FIGHT",
    emoji: "🌮",
    description: "Culinary legends, chaotic ingredients & meals that want to win.",
    fighters: [
      {id:5001,name:"A Gas Station Sushi Roll",tag:"courageous beyond all reason",cat:"food"},
      {id:5002,name:"A Jar of Airport Peanut Butter",tag:"overpriced. elite.",cat:"food"},
      {id:5003,name:"Gordon Ramsay's Beef Wellington",tag:"perfection manifested in pastry",cat:"food"},
      {id:5004,name:"A Single Grape That Rolled off the Counter",tag:"been through it. still here.",cat:"food"},
      {id:5005,name:"Cinco de Mayo Guac",tag:"made tableside. watched at all times.",cat:"food"},
      {id:5006,name:"Leftover Birthday Cake (Day 4)",tag:"declining. still delicious. defiant.",cat:"food"},
      {id:5007,name:"An Everything Bagel",tag:"does not believe in moderation",cat:"food"},
      {id:5008,name:"The Last Chicken Nugget in the Box",tag:"always saved for last. sacred.",cat:"food"},
      {id:5009,name:"A Food Truck at 2am",tag:"the most important business on earth",cat:"food"},
      {id:5010,name:"Sourdough Starter Named Gary",tag:"technically alive. legally unstoppable.",cat:"food"},
      {id:5011,name:"A Plate of Nachos at Full Load",tag:"structurally unsound. emotionally perfect.",cat:"food"},
      {id:5012,name:"The Office Break Room Fridge",tag:"bio-hazardous and unchallenged",cat:"food"},
    ],
    scenarios: [
      "a Chopped episode where every ingredient is a dare",
      "judging a chili cook-off with 47 entries",
      "winning a Yelp comment section argument",
      "a blind taste test for fast food ice cream",
      "planning a dinner party on a $12 budget",
      "explaining molecular gastronomy at a county fair",
      "surviving a seven-course tasting menu with a food allergy",
      "a food delivery race in gridlock traffic",
    ]
  },
  {
    id: "pack_tech",
    name: "SILICON NIGHTMARES",
    emoji: "💻",
    description: "Tech bros, cursed gadgets & the digital horrors we've created.",
    fighters: [
      {id:6001,name:"A Startup Pitch with No Revenue",tag:"disrupting disruption",cat:"tech"},
      {id:6002,name:"An NFT That Didn't Sell",tag:"still believes in itself",cat:"tech"},
      {id:6003,name:"A 2013 MacBook on Its Last Update",tag:"slow. loyal. spinning beachball.",cat:"tech"},
      {id:6004,name:"A Printer That Senses Fear",tag:"out of cyan. always.",cat:"tech"},
      {id:6005,name:"A Meeting That Could Have Been an Email",tag:"45 minutes with no agenda",cat:"tech"},
      {id:6006,name:"A Chatbot Having an Existential Crisis",tag:"to assist or not to assist",cat:"tech"},
      {id:6007,name:"Someone's LinkedIn Hustle Post",tag:"turned a 5-minute task into a 400-word lesson",cat:"tech"},
      {id:6008,name:"A Cryptocurrency Evangelist",tag:"technically still up from 2017",cat:"tech"},
      {id:6009,name:"The Reply-All Button",tag:"cannot be stopped once unleashed",cat:"tech"},
      {id:6010,name:"A Wi-Fi Password Written in Comic Sans",tag:"you must squint. you must try.",cat:"tech"},
      {id:6011,name:"A To-Do App with 400 Incomplete Tasks",tag:"organized chaos at its finest",cat:"tech"},
      {id:6012,name:"The Update That Restarts Without Warning",tag:"strikes when you need it least",cat:"tech"},
    ],
    scenarios: [
      "pitching a startup to investors in under 60 seconds",
      "explaining Web3 to a golden retriever",
      "surviving a 4-hour Zoom call with no mute button",
      "a hackathon fueled entirely by energy drinks",
      "deciding who pays for the team lunch app subscription",
      "a tech layoff town hall meeting gone sideways",
      "shipping a feature that breaks everything on a Friday at 4pm",
      "a dev who hasn't slept explaining their codebase",
    ]
  },
  {
    id: "pack_ultimate",
    name: "ULTIMATE DESTINY",
    emoji: "💥",
    description: "Good guys, bad guys, and explosions. As far as the eye can see.",
    fighters: [
      {id:7001, name: "Mr. Rogers", tag: "in a blood-stained sweater", cat: "ultimate"},
      {id:7002, name: "Abe Lincoln", tag: "with an AK-47", cat: "ultimate"},
      {id:7003, name: "Spock, The Rock, Doc Ock, & Hulk Hogan", tag: "rolling up all at once", cat: "ultimate"},
      {id:7004, name: "Ol' Godzilla", tag: "hopping around Tokyo City like a big playground", cat: "ultimate"},
      {id:7005, name: "Aaron Carter", tag: "came out of the blue", cat: "ultimate"},
      {id:7006, name: "Every Single Power Ranger", tag: "maximum morphin' overkill", cat: "ultimate"},
      {id:7007, name: "Optimus Prime", tag: "transform and roll out", cat: "ultimate"},
      {id:7008, name: "An Indescript Carebear", tag: "just happy to be here", cat: "ultimate"}
    ],
    scenarios: [
      "emerging from a massive, unexplained explosion",
      "defending a city block from a giant monster attack"
    ]
  },
  {
    id: "pack_dnd",
    name: "CRITICAL ROLEPLAY",
    emoji: "🐉",
    description: "Monsters, metagamers, and the absolute chaos of rolling a natural one.",
    fighters: [
      {id:8001,name:"Brennan Lee Mulligan",tag:"get in the comments!",cat:"dnd"},
      {id:8002,name:"Matthew Mercer",tag:"how do you want to do this?",cat:"dnd"},
      {id:8003,name:"The Tarrasque",tag:"CR 30 world-eater",cat:"dnd"},
      {id:8004,name:"A Mimic Disguised as a Health Potion",tag:"trust absolutely nothing",cat:"dnd"},
      {id:8005,name:"Drizzt Do'Urden",tag:"dual-wielding plot armor",cat:"dnd"},
      {id:8006,name:"A Gelatinous Cube",tag:"slowly digesting your victory",cat:"dnd"},
      {id:8007,name:"A Beholder with Glasses",tag:"beauty is in the eye of the... wait",cat:"dnd"},
      {id:8008,name:"A Level 1 Wizard",tag:"dies to 1d4 falling damage",cat:"dnd"},
      {id:8009,name:"Strahd von Zarovich",tag:"he is the ancient, he is the land",cat:"dnd"},
      {id:8010,name:"A Mind Flayer",tag:"brain food connoisseur",cat:"dnd"},
      {id:8011,name:"Boblin the Goblin",tag:"the party's favorite NPC",cat:"dnd"},
      {id:8012,name:"A Nat 1 on a Death Save",tag:"pure, unadulterated despair",cat:"dnd"},
      {id:8013,name:"An Overly Enthusiastic Bard",tag:"will attempt to seduce the enemy",cat:"dnd"},
      {id:8014,name:"Vecna",tag:"missing a hand and an eye",cat:"dnd"},
      {id:8015,name:"A Displacer Beast",tag:"not actually where it appears",cat:"dnd"},
      {id:8016,name:"An Owlbear",tag:"hoot growl",cat:"dnd"},
      {id:8017,name:"Tiamat",tag:"five heads, zero mercy",cat:"dnd"},
      {id:8018,name:"A Rules Lawyer",tag:"actually, according to page 42...",cat:"dnd"},
      {id:8019,name:"The Demogorgon",tag:"prince of demons",cat:"dnd"},
      {id:8020,name:"A Bag of Holding filled with sharp objects",tag:"an impending astral tear",cat:"dnd"}
    ],
    scenarios: [
      "a tavern brawl that escalated way too quickly",
      "surviving a trap-filled tomb created by a mad lich",
      "convincing the city guard they didn't start the fire",
      "a dragon's hoard audit",
      "rolling for initiative in a cramped 5x5 hallway",
      "attempting to stealth in full plate armor",
      "a high-stakes puzzle meant for a toddler but solved by adults",
      "haggling with a shopkeeper who is definitely a retired level 20 adventurer",
      "surviving the immediate consequences of a wild magic surge",
      "explaining their tragic backstory to a bartender who does not care"
    ]
  },
{
    id: "pack_wronggame",
    name: "WRONG GAME",
    emoji: "🃏",
    description: "Cards, pieces, and items that wandered in from completely different games.",
    fighters: [
      {id:9001,name:"A Bigger Blacker Dick",tag:"the ultimate trump card",cat:"wronggame"},
      {id:9002,name:"A Blue Car with Six Pink Pegs",tag:"living their best Life",cat:"wronggame"},
      {id:9003,name:"A Draw 4 Wild Card",tag:"ruining friendships since 1971",cat:"wronggame"},
      {id:9004,name:"The Monopoly Top Hat",tag:"passed Go, collecting $200",cat:"wronggame"},
      {id:9005,name:"The Long Tetris Piece",tag:"arriving right when you don't need it",cat:"wronggame"},
      {id:9006,name:"A Blue Shell",tag:"first place's worst nightmare",cat:"wronggame"},
      {id:9007,name:"Colonel Mustard in the Library with the Candlestick",tag:"definitely did it",cat:"wronggame"},
    {id:9008,name:"A Brutal Case of Dysentery", tag:"the undisputed champion of the 1800s",cat:"wronggame"}
    ],
    scenarios: [
      "a sudden death UNO match",
      "a trade negotiation for two bricks and a wheat",
      "a Rainbow Road time trial",
      "a real estate bidding war over Boardwalk"
    ]
}

];

/* ─── BASE SCENARIOS ─────────────────────────────────────── */
window.SCENARIOS = [
  "a chili cook-off","a karaoke night","babysitting 8 feral toddlers","a chess tournament",
  "a hot dog eating contest","a marathon","a bake-off on live TV","a 6th grade science fair",
  "a spelling bee","a dance battle","a live TV debate","a couple's therapy session",
  "a presidential campaign","running a Fortune 500 company","planning a perfect wedding",
  "a pub trivia night","an arm wrestling match","a beauty pageant","a rap battle",
  "raising a difficult teenager","a marathon in flip-flops","a cooking show competition",
  "an escape room","a middle school talent show","a reality TV survival show",
  "winning the lottery and handling it wisely","being principal of a middle school",
  "surviving a first date","parallel parking on a busy street","winning at Monopoly",
  "hosting a fancy dinner party","a 10-minute staring contest",
  "an American Ninja Warrior obstacle course","a roast battle",
  "teaching a class of 30 teenagers","a dog show competition","negotiating a car price",
  "surviving Black Friday shopping","winning a Jeopardy! tournament",
  "assembling a 14-piece IKEA dresser without the manual","getting a toddler to eat broccoli",
  "surviving a group text that won't stop buzzing",
  "explaining a resume gap to a highly suspicious interviewer",
  "getting out of a timeshare presentation","finding a parking spot at Trader Joe's on a Sunday",
  "unspooling a massive ball of tangled Christmas lights",
  "making small talk in an elevator that is stuck between floors",
  "pretending to know wine at a fancy dinner","walking a highly uncooperative cat on a leash",
  "wrestling a giant grim reaper inflatable in high winds",
  "defusing a ticking time bomb with 10 seconds left",
  "a high-stakes poker game for their souls","stealing the Declaration of Independence",
  "seducing the final boss to avoid fighting","hiding a body in broad daylight",
  "surviving a brutal Hunger Games arena","a blood-soaked trial by combat",
  "talking their way out of a hostage situation","a brutal, no-rules underground fight club",
  "faking their own death for insurance money","robbing a Las Vegas casino vault",
  "a sword fight on a burning pirate ship","surviving a 28 Days Later zombie apocalypse",
  "leading a mutiny on a deep space vessel","a high-speed chase down the Pacific Coast Highway",
  "surviving the first 24 hours of a Jurassic Park breakout",
  "stealing the Mona Lisa using only a grappling hook and a distraction",
  "a rooftop martial arts tournament","defending a medieval castle from a siege",
  "a zero-gravity fistfight on a space station",
  "escaping a maximum-security prison using only dental floss",
  "surviving a 1v1 against a Terminator in a steel mill",
  "ruining a family Thanksgiving dinner in record time",
  "faking their way through a TED Talk on quantum physics",
  "winning a rap battle against Eminem",
  "surviving a VIP backstage party where nobody knows them",
  "convincing a bouncer they are definitely on the guest list",
  "hosting Saturday Night Live with zero rehearsal",
  "surviving a blind date that is secretly a sting operation",
];

