/* ─── FIGHTERS ──────────────────────────────────────────── */
window.FIGHTERS = [
  // Items
  {id:1,name:"100 Rubber Ducks",emoji:"🦆",tag:"squeaky and unstoppable",description:"A coordinated flock of rubber ducks with collective swarm intelligence",cat:"items"},
  {id:2,name:"A Roomba",emoji:"🤖",tag:"tireless floor guardian",description:"Autonomous robot vacuum with relentless determination",cat:"items"},
  {id:3,name:"A Pool Noodle",emoji:"🏊",tag:"floats above the competition",description:"Flexible foam flotation device with surprising defensive capabilities",cat:"items"},
  {id:4,name:"A Microwave",emoji:"🔥",tag:"beeps with authority",description:"Kitchen appliance with heating power and attention-demanding alerts",cat:"items"},
  {id:5,name:"An Entire Costco",emoji:"🏪",tag:"bulk power, baby",description:"Warehouse-scale retail establishment with infinite inventory",cat:"items"},
  {id:6,name:"A Shopping Cart",emoji:"🛒",tag:"rolling chaos energy",description:"Metal cart with momentum, momentum management issues, and zero brakes",cat:"items"},
  {id:7,name:"A 2001 Honda Civic",emoji:"🚗",tag:"still running somehow",description:"Reliable economy car with 20+ years of proven durability",cat:"items"},
  {id:8,name:"A Fidget Spinner",emoji:"⚙️",tag:"peak 2017 energy",description:"Bearing-based spinning toy with hypnotic rotational properties",cat:"items"},
  {id:9,name:"A Dyson Vacuum",emoji:"💨",tag:"sucks at losing",description:"High-end suction technology with premium engineering",cat:"items"},
  {id:10,name:"A Slightly Damp Sock",emoji:"🧦",tag:"uncomfortably determined",description:"Moisture-laden hosiery with stubborn persistence",cat:"items"},
  {id:11,name:"The Last Slice of Pizza",emoji:"🍕",tag:"worth fighting for",description:"Final remaining portion of a shared meal - universally coveted",cat:"items"},
  {id:12,name:"A Vending Machine",emoji:"🥤",tag:"refuses to give up OR give change",description:"Mechanical dispenser with a will of its own and questionable accuracy",cat:"items"},
  {id:13,name:"A Broken Umbrella",emoji:"☂️",tag:"still showing up",description:"Damaged rain shield that technically still functions",cat:"items"},
  {id:14,name:"A Very Sharp Pencil",emoji:"✏️",tag:"pointedly dangerous",description:"Freshly sharpened writing implement with needle-like precision",cat:"items"},
  // Animals
  {id:15,name:"1 Horse",emoji:"🐴",tag:"neigh means yes, I win",description:"Domesticated equine with strength, speed, and herd instincts",cat:"animals"},
  {id:16,name:"A Golden Retriever",emoji:"🐕",tag:"good boy energy is unstoppable",description:"Loyal dog breed known for intelligence, athleticism, and unwavering dedication",cat:"animals"},
  {id:17,name:"100 Squirrels",emoji:"🐿️",tag:"chaotic nut energy",description:"Nimble rodents with acrobatic prowess and unpredictable behavior",cat:"animals"},
  {id:18,name:"A Honey Badger",emoji:"🦡",tag:"don't care, won't care",description:"Fearless mustelid with legendary combativeness and no natural predators",cat:"animals"},
  {id:19,name:"A Murder of Crows",emoji:"🐦",tag:"plotting since dawn",description:"Intelligent corvids known for problem-solving and tactical coordination",cat:"animals"},
  {id:20,name:"A Capybara",emoji:"🦫",tag:"terrifyingly chill",description:"Largest living rodent, herbivorous and surprisingly calm under pressure",cat:"animals"},
  {id:21,name:"A Swarm of Bees",emoji:"🐝",tag:"democracy in action",description:"Cooperative insects with collective intelligence and defensive weaponry",cat:"animals"},
  {id:22,name:"A Florida Man",emoji:"👨",tag:"headlines write themselves",description:"Human specimen with legendary unpredictability and survival instincts",cat:"animals"},
  {id:23,name:"A Single Goose",emoji:"🦆",tag:"no mercy, no remorse",description:"Aggressive waterfowl known for territorial behavior and unexpected ferocity",cat:"animals"},
  {id:24,name:"A Raccoon With Nothing to Lose",emoji:"🦝",tag:"trash panda champion",description:"Cunning opportunist with dexterous paws and problem-solving intelligence",cat:"animals"},
  {id:25,name:"50 Ferrets in a Trenchcoat",emoji:"🧥",tag:"organized chaos",description:"Coordinated group of small carnivores disguised as a single entity",cat:"animals"},
  {id:26,name:"A Golden Retriever with a PhD",emoji:"🐕‍🎓",tag:"academically good boy",description:"Intellectually superior canine with doctorate-level knowledge and loyalty",cat:"animals"},
  {id:27,name:"A Sleepy Sloth",emoji:"🦥",tag:"eventually gets there",description:"Deliberate mammal that operates on a fundamentally different time scale",cat:"animals"},
  {id:28,name:"A Grizzly Bear",emoji:"🐻",tag:"doesn't negotiate",description:"Apex predator with raw power, intimidation, and territorial dominance",cat:"animals"},
  // Pop Culture
  {id:29,name:"SpongeBob SquarePants",emoji:"🧽",tag:"I'm ready!",description:"Optimistic sea sponge with enthusiasm and work ethic transcending reality",cat:"popculture"},
  {id:30,name:"Shrek",emoji:"👹",tag:"this is my swamp, I win",description:"Ogre warrior with unexpected depth and an impenetrable fortress",cat:"popculture"},
  {id:31,name:"The Mandalorian",emoji:"🪓",tag:"this is the way",description:"Professional bounty hunter with advanced weaponry and tactical expertise",cat:"popculture"},
  {id:32,name:"John Wick",emoji:"🔫",tag:"breathes pure revenge",description:"Legendary assassin with unmatched combat skills and ruthless determination",cat:"popculture"},
  {id:33,name:"Baby Yoda (Grogu)",emoji:"👶",tag:"force is strong with this snack",description:"Ancient Force-sensitive being with incredible potential and cuteness",cat:"popculture"},
  {id:34,name:"Walter White",emoji:"🧪",tag:"I am the one who wins",description:"Chemistry genius who becomes a ruthless crime lord through intellect",cat:"popculture"},
  {id:35,name:"Tony Stark",emoji:"🤖",tag:"genius. billionaire. winner.",description:"Genius engineer and billionaire philanthropist in powered armor",cat:"popculture"},
  {id:36,name:"Gollum",emoji:"💍",tag:"my precious... victory",description:"Ancient creature obsessed with singular objects and possessive tactics",cat:"popculture"},
  {id:37,name:"Darth Vader",emoji:"🎭",tag:"heavy breathing into trophies",description:"Sith Lord with immense Force power and an indomitable presence",cat:"popculture"},
  {id:38,name:"Thanos",emoji:"💪",tag:"perfectly balanced, as all wins should be",description:"Cosmic titan with reality-altering power and philosophical conviction",cat:"popculture"},
  {id:39,name:"The Terminator",emoji:"🤖",tag:"I'll be back... with the W",description:"Sentient machine from the future with single-minded purpose",cat:"popculture"},
  {id:40,name:"Captain Jack Sparrow",emoji:"🏴‍☠️",tag:"savvy?",description:"Unpredictable pirate captain with unconventional tactics and charm",cat:"popculture"},
  {id:41,name:"Gandalf",emoji:"🧙",tag:"you shall not LOSE",description:"Powerful wizard with ancient wisdom and devastating magical abilities",cat:"popculture"},
  {id:42,name:"Hermione Granger",emoji:"📚",tag:"technically always right",description:"Brilliant witch with encyclopedic knowledge and resourcefulness",cat:"popculture"},
  {id:43,name:"Michael Scott",emoji:"👔",tag:"that's what she said... I win",description:"Regional manager with charisma, humor, and unexpected competence",cat:"popculture"},
  {id:44,name:"Ron Swanson",emoji:"🪵",tag:"government-hating champion",description:"Libertarian bureaucrat with woodworking skills and unwavering principles",cat:"popculture"},
  {id:45,name:"Dwight Schrute",emoji:"🌽",tag:"assistant TO the winner",description:"Intense salesman with martial arts training and fierce loyalty",cat:"popculture"},
  {id:46,name:"The Joker",emoji:"🤡",tag:"why so serious about losing?",description:"Chaotic villain with unpredictable methods and psychological tactics",cat:"popculture"},
  {id:47,name:"Deadpool",emoji:"💔",tag:"fourth wall? more like fourth WIN",description:"Mercenary antihero with accelerated healing and comedic sensibility",cat:"popculture"},
  {id:48,name:"Mario",emoji:"🍄",tag:"it'sa me, the winner!",description:"Italian plumber with jump mechanics and persistent can-do attitude",cat:"popculture"},
  {id:49,name:"Sonic the Hedgehog",emoji:"⚡",tag:"gotta go fast to victory",description:"Speedster hedgehog with attitude and blue blur momentum",cat:"popculture"},
  {id:50,name:"Pikachu",emoji:"⚡",tag:"I choose YOU to lose",description:"Electric-type Pokémon with signature thunderbolt attack",cat:"popculture"},
  {id:51,name:"Donkey Kong",emoji:"🦍",tag:"banana-powered greatness",description:"Powerful ape with primate strength and jungle territory",cat:"popculture"},
  {id:52,name:"Link (from Zelda)",emoji:"🗡️",tag:"silent but absolutely deadly",description:"Courageous hero with legendary sword and puzzle-solving prowess",cat:"popculture"},
  {id:53,name:"Patrick Star",emoji:"⭐",tag:"is mayonnaise a strategy?",description:"Pink starfish with surprising strength and unconventional thinking",cat:"popculture"},
  {id:54,name:"Squidward",emoji:"🎺",tag:"artistically superior at everything",description:"Cultured cephalopod with artistic talent and disdainful attitude",cat:"popculture"},
  {id:55,name:"Homer Simpson",emoji:"🍩",tag:"mmm... winning",description:"Nuclear safety inspector with surprising problem-solving abilities",cat:"popculture"},
  {id:56,name:"Bart Simpson",emoji:"🛹",tag:"don't have a cow, man",description:"Mischievous prankster with quick thinking and skateboard skills",cat:"popculture"},
  {id:57,name:"Peter Griffin",emoji:"👨",tag:"this reminds me of the time I won...",description:"Family patriarch with chaotic anecdotes and unexpected competence",cat:"popculture"},
  {id:58,name:"Stewie Griffin",emoji:"👶",tag:"blast! still winning.",description:"Brilliant infant with diabolical plans and incredible intellect",cat:"popculture"},
  {id:59,name:"Rick Sanchez",emoji:"🥤",tag:"wubba lubba dub dub, I win",description:"Genius scientist with advanced technology and nihilistic attitude",cat:"popculture"},
  {id:60,name:"The Incredible Hulk",emoji:"💚",tag:"Hulk SMASH competition",description:"Gamma-irradiated giant with immense strength and emotional power",cat:"popculture"},
  {id:61,name:"Spider-Man",emoji:"🕷️",tag:"with great power comes great W's",description:"Superhero with web-slinging abilities and responsibility-driven ethics",cat:"popculture"},
  {id:62,name:"Batman",emoji:"🦇",tag:"I'm Batman. I win.",description:"Billionaire vigilante with gadgets, training, and detective skills",cat:"popculture"},
  {id:63,name:"Wednesday Addams",emoji:"🖤",tag:"joylessly dominant in all things",description:"Deadpan goth with lethal skills and unsettling competence",cat:"popculture"},
  {id:64,name:"Shaggy (at full power)",emoji:"🍗",tag:"using 0.01% of his strength",description:"Laid-back mystery solver with untapped cosmic potential",cat:"popculture"},
  {id:65,name:"Gru (from Despicable Me)",emoji:"🎈",tag:"has a plan. an elaborate plan.",description:"Supervillain with meticulous planning and surprising heart",cat:"popculture"},
  {id:66,name:"The Mandela Effect",emoji:"🌀",tag:"wins in every alternate timeline",description:"Phenomenon that exists differently across various realities",cat:"popculture"},
  // Celebs
  {id:67,name:"Gordon Ramsay",emoji:"👨‍🍳",tag:"this victory is RAW",description:"Celebrity chef known for culinary excellence and fiery critique",cat:"celebs"},
  {id:68,name:"Dwayne Johnson",emoji:"💪",tag:"can you smell what The Rock is winning?",description:"Action star and former wrestler with charisma and athleticism",cat:"celebs"},
  {id:69,name:"Oprah",emoji:"📺",tag:"YOU get a win! YOU get a win!",description:"Media mogul with influence, wealth, and generous spirit",cat:"celebs"},
  {id:70,name:"Bob Ross",emoji:"🎨",tag:"happy little victories",description:"Gentle painter with soothing voice and genuine kindness",cat:"celebs"},
  {id:71,name:"Mr. T",emoji:"🥊",tag:"I pity the fool who loses to me",description:"Actor and bodyguard with iconic catchphrases and gold chains",cat:"celebs"},
  {id:72,name:"Chuck Norris",emoji:"🤐",tag:"Chuck doesn't compete. He just wins.",description:"Action star and martial artist with legendary toughness",cat:"celebs"},
  {id:73,name:"Nicolas Cage",emoji:"🎬",tag:"NOT THE BEES... but still winning",description:"Actor known for intense performances and eccentric energy",cat:"celebs"},
  {id:74,name:"Keanu Reeves",emoji:"😊",tag:"breathtaking victory",description:"Actor and musician with genuine kindness and action prowess",cat:"celebs"},
  {id:75,name:"Danny DeVito",emoji:"🍆",tag:"surprisingly and terrifyingly good",description:"Actor and producer with comedic timing and tough persona",cat:"celebs"},
  {id:76,name:"Morgan Freeman (narrating)",emoji:"🎙️",tag:"and then... they won",description:"Legendary narrator whose voice makes any victory feel epic",cat:"celebs"},
  {id:77,name:"Betty White's Ghost",emoji:"👻",tag:"still the most powerful being",description:"Eternally beloved entertainer with decades of cultural impact",cat:"celebs"},
  {id:78,name:"David Attenborough",emoji:"🦁",tag:"narrating victory into existence",description:"Naturalist and broadcaster with authoritative documentary voice",cat:"celebs"},
  {id:79,name:"Gordon Ramsay's Ego",emoji:"📈",tag:"a separate, larger entity",description:"Independent consciousness of professional pride and standards",cat:"celebs"},
  // Memes
  {id:80,name:"The Doge",emoji:"🐕",tag:"very win. much champion. wow.",description:"Shiba Inu meme icon with broken English mystique",cat:"memes"},
  {id:81,name:"Grumpy Cat",emoji:"😾",tag:"already lost. doesn't care.",description:"Perpetually dissatisfied feline with cult following",cat:"memes"},
  {id:82,name:"Harambe's Ghost",emoji:"🦍",tag:"still an icon. still powerful.",description:"Legendary gorilla whose memory transcends meme culture",cat:"memes"},
  {id:83,name:"This Is Fine Dog",emoji:"🔥",tag:"winning while everything burns",description:"Stoic canine coping with chaos through acceptance",cat:"memes"},
  {id:84,name:"Big Chungus",emoji:"🐰",tag:"chonky and absolutely unstoppable",description:"Thicc Bugs Bunny with overwhelming presence",cat:"memes"},
  {id:85,name:"Nyan Cat",emoji:"🌈",tag:"leaving rainbows of victory",description:"Pixel cat flying through space with hypnotic repetition",cat:"memes"},
  {id:86,name:"Salt Bae",emoji:"🧂",tag:"seasoning the competition",description:"Chef internet personality known for dramatic salt sprinkling",cat:"memes"},
  {id:87,name:"1000 Pigeons in a Trenchcoat",emoji:"🧥",tag:"definitely a human. definitely winning.",description:"Coordinated flock of birds in sophisticated disguise",cat:"memes"},
  {id:88,name:"Area 51 Naruto Runner",emoji:"🏃",tag:"they can't stop all of us",description:"Meme icon representing chaotic 2019 raid mentality",cat:"memes"},
  {id:89,name:"The Confused Math Lady",emoji:"🤔",tag:"calculating exactly how to win",description:"Meme symbol of befuddlement and mathematical struggle",cat:"memes"},
  {id:90,name:"'To Be Continued' Arrow",emoji:"➡️",tag:"victory is inevitable",description:"JoJo's reference representing unstoppable momentum",cat:"memes"},
  {id:91,name:"Wojak",emoji:"😐",tag:"painfully relatable winner",description:"Simplified figure meme representing existential relatable experiences",cat:"memes"},
  // Roles
  {id:92,name:"A Kindergarten Teacher",emoji:"🍎",tag:"survived worse, will survive this",description:"Educator managing chaos and shaping young minds with patience",cat:"roles"},
  {id:93,name:"A Divorced Dad",emoji:"🚗",tag:"just bought a sports car and a grill",description:"Father starting fresh with renewed hobbies and confidence",cat:"roles"},
  {id:94,name:"A Karen",emoji:"☎️",tag:"wants to speak to the referee",description:"Customer with high expectations and assertive communication style",cat:"roles"},
  {id:95,name:"An Overworked Barista",emoji:"☕",tag:"has seen dark things. dark things.",description:"Coffee shop worker with wisdom earned from human observation",cat:"roles"},
  {id:96,name:"A Tired Nurse",emoji:"💉",tag:"no days off. no losses.",description:"Healthcare worker with unbreakable resilience and dedication",cat:"roles"},
  {id:97,name:"A Mall Santa",emoji:"🎅",tag:"knows who's been naughty",description:"Seasonal character accumulating data on children's behavior",cat:"roles"},
  {id:98,name:"A DMV Employee",emoji:"📋",tag:"outlasted everyone, will outlast you",description:"Government worker with eternal patience and procedural knowledge",cat:"roles"},
  {id:99,name:"The Guitar Guy at Parties",emoji:"🎸",tag:"Wonderwall your way to victory",description:"Musical enthusiast with rotating setlist of familiar songs",cat:"roles"},
  {id:100,name:"A Philosophy Major",emoji:"🧠",tag:"but what even IS winning?",description:"Academic questioning fundamental nature of competition",cat:"roles"},
  {id:101,name:"A Retired Ninja",emoji:"🥷",tag:"semi-retired. still absolutely deadly.",description:"Former assassin with preserved combat skills",cat:"roles"},
  {id:102,name:"50 Kindergarteners",emoji:"👶",tag:"utter chaos. maximum energy.",description:"Group of young children in collective chaotic state",cat:"roles"},
  {id:103,name:"A Toddler with Scissors",emoji:"✂️",tag:"certified certified menace",description:"Young child wielding sharp objects with no impulse control",cat:"roles"},
  {id:104,name:"An Immortal Grandmother",emoji:"👵",tag:"seen it all. still going.",description:"Ageless matriarch with accumulated wisdom and vitality",cat:"roles"},
  {id:105,name:"The Entire Cast of Mamma Mia",emoji:"🎭",tag:"ABBA-solutely dominant",description:"Ensemble production with infectious musical energy",cat:"roles"},
  {id:106,name:"A LinkedIn Influencer",emoji:"💼",tag:"turning this loss into thought leadership",description:"Social media personality monetizing professional networking",cat:"roles"},
  {id:107,name:"A World's Most Patient Librarian",emoji:"📚",tag:"quiet strength, loud results",description:"Information specialist with exceptional calm and knowledge",cat:"roles"},
  // Abstract
  {id:108,name:"Time Itself",emoji:"⏳",tag:"always wins eventually",description:"Temporal force that inevitably erodes all resistance",cat:"abstract"},
  {id:109,name:"The Economy",emoji:"💰",tag:"crashing its way to first place",description:"Complex financial system with unpredictable movements",cat:"abstract"},
  {id:110,name:"Gravity",emoji:"⬇️",tag:"inevitable. like my victory.",description:"Fundamental force pulling all things downward persistently",cat:"abstract"},
  {id:111,name:"A 6-Year-Old Who Just Learned About Dinosaurs",emoji:"🦕",tag:"ACTUALLY THEY COULD FLY",description:"Child with newfound knowledge and passionate debate style",cat:"abstract"},
  {id:112,name:"An AI Chatbot",emoji:"🤖",tag:"just here to assist your defeat",description:"Artificial intelligence providing contextual assistance",cat:"abstract"},
  {id:113,name:"The Concept of Mondays",emoji:"📅",tag:"ruins everything, always wins",description:"Weekly cycle universally recognized as difficult",cat:"abstract"},
  {id:114,name:"The Algorithm",emoji:"🔍",tag:"knows what you want before you do",description:"Computational system predicting human behavior patterns",cat:"abstract"},
  {id:115,name:"The Last 2% of Your Phone Battery",emoji:"🔋",tag:"absolute psychological terror",description:"Dwindling power supply creating existential anxiety",cat:"abstract"},
  {id:116,name:"A Brutal Case of Writer's Block",emoji:"📝",tag:"staring at a blank page forever",description:"Creative paralysis preventing any forward progress",cat:"abstract"},
  {id:117,name:"The Existential Dread of a Perfectly Restocked Retail Aisle",emoji:"🏬",tag:"everything is where it belongs, but at what cost?",description:"Eerie perfection creating philosophical unease",cat:"abstract"},
  {id:118,name:"A 99-Day Digital Streak",emoji:"📱",tag:"pure, unadulterated, sleep-deprived commitment",description:"Extended consecutive participation motivated by numbers",cat:"abstract"},
  {id:119,name:"A mid 2000s Pop Punk Song Title",emoji:"🎵",tag:"misunderstood but incredibly loud",description:"Emotionally charged musical reference with nostalgia",cat:"abstract"},
  {id:120,name:"An Unpolished Fluorite Crystal",emoji:"💜",tag:"natural, bespoke, and hard as rock",description:"Raw mineral specimen with natural geometric perfection",cat:"abstract"},
  {id:121,name:"The Sunk Cost Fallacy",emoji:"💸",tag:"you're already this far in, might as well win",description:"Cognitive bias driving commitment based on past investment",cat:"abstract"},
  {id:122,name:"Dodger Stadium Traffic",emoji:"🚙",tag:"an inescapable, soul-crushing force",description:"Los Angeles parking lot creating collective suffering",cat:"abstract"},
  {id:123,name:"Unearned Confidence",emoji:"😎",tag:"doesn't know what's happening, still winning",description:"Unfounded self-assurance superseding actual competence",cat:"abstract"},
  {id:124,name:"A Really Good Iced Coffee",emoji:"☕",tag:"the only thing holding it all together",description:"Caffeinated beverage providing essential daily support",cat:"abstract"},
  {id:125,name:"The Concept of 'Maybe Later'",emoji:"⏰",tag:"undefeated champion of procrastination",description:"Procrastination philosophy defeating all urgency",cat:"abstract"},
];

/* ─── EXPANSION PACKS ────────────────────────────────────── */
window.EXPANSION_PACKS = [
  {
    id: "pack_history",
    name: "HISTORY'S WEIRDEST",
    emoji: "🏛️",
    description: "Ancient rulers, famous failures & historical wildcards. Time travel sold separately.",
    fighters: [
      {id:2001,name:"Genghis Khan on a Monday",tag:"conquered empires before breakfast",description:"World-conquering warlord at peak Monday morning aggression and caffeine-free fury",cat:"history"},
      {id:2002,name:"Cleopatra's PR Team",tag:"aggressively spinning the narrative",description:"Elite communications staff managing the most powerful personal brand in the ancient world",cat:"history"},
      {id:2003,name:"A Viking Who Just Discovered Coffee",tag:"already dangerous. now caffeinated.",description:"Norse raider with caffeinated fury, zero chill, and a brand new reason to pillage",cat:"history"},
      {id:2004,name:"Napoleon's Height Debate",tag:"surprisingly not the issue here",description:"The most persistently argued misconception in military history, still fighting for its life",cat:"history"},
      {id:2005,name:"Sun Tzu, But For Trivia Night",tag:"all warfare is based on deception",description:"Ancient military strategist applying Art of War principles to pop culture and sports categories",cat:"history"},
      {id:2006,name:"A Victorian Ghost Hunter",tag:"100% certain, 0% accurate",description:"Paranormal investigator armed with false confidence, a candle, and zero verifiable evidence",cat:"history"},
      {id:2007,name:"An Egyptian Pharaoh with a Yelp Account",tag:"3 stars. pyramid was drafty.",description:"God-king leveraging modern consumer complaint infrastructure against ancient construction crews",cat:"history"},
      {id:2008,name:"Julius Caesar's Last Text Draft",tag:"et tu, autocorrect?",description:"Final unsent message corrupted simultaneously by betrayal and autocorrect algorithm",cat:"history"},
      {id:2009,name:"A Plague Doctor with Social Anxiety",tag:"the mask is for health reasons. definitely.",description:"Medieval physician protected by leather beak mask and profound introversion disguised as professionalism",cat:"history"},
      {id:2010,name:"The Loch Ness Monster's Publicist",tag:"managing impossible expectations since 1933",description:"Career professional managing a client with zero verifiable public appearances since 1933",cat:"history"},
      {id:2011,name:"A Spartan Who Does Yoga Now",tag:"come back with your shield or on it... but also namaste",description:"Elite warrior channeling ancient combat discipline through contemporary wellness and breathwork practices",cat:"history"},
      {id:2012,name:"Marie Curie's Glow",tag:"radioactively unstoppable",description:"Radioactive legacy of the most luminous and persistently brilliant scientist in recorded history",cat:"history"},
    ],
    scenarios: [
      "a medieval jousting tournament on Segways",
      "writing a Yelp review for the Colosseum",
      "speed-running the construction of the Great Wall",
      "explaining the internet to Aristotle",
      "hosting a Renaissance Fair on a cruise ship",
      "a chariot race through downtown LA",
      "negotiating a peace treaty using only emojis",
      "planning Cleopatra's bachelorette party",
    ]
  },
  {
    id: "pack_sports",
    name: "ATHLETIC CHAOS",
    emoji: "🏆",
    description: "Sports legends, cursed athletes & the ultimate battle of who actually has game.",
    fighters: [
      {id:3001,name:"A Youth Soccer Coach in Overtime",tag:"THIS IS NOT A DRILL, KYLE",description:"Volunteer parent teetering on a breakdown with a whistle, a clipboard, and everything on the line",cat:"sports"},
      {id:3002,name:"An Olympian Who Peaked in 2008",tag:"technically still medaled",description:"Former gold medalist with a podium photo, a story for every occasion, and a glory era to defend",cat:"sports"},
      {id:3003,name:"A Little League Parent",tag:"would like to speak to the umpire",description:"Sideline force of nature who takes children's recreational baseball deeply and dangerously personally",cat:"sports"},
      {id:3004,name:"A Cornhole Champion",tag:"don't underestimate the bags",description:"Backyard games legend with tournament-level arc accuracy and quietly devastating confidence",cat:"sports"},
      {id:3005,name:"The Entire 1992 Dream Team",tag:"just absolutely overkill",description:"Assembled coalition of the greatest basketball players ever assembled simultaneously in one place",cat:"sports"},
      {id:3006,name:"A Horse That Only Runs for Snacks",tag:"motivated. selectively.",description:"Equine athlete with elite speed capability deployed exclusively under the right gustatory conditions",cat:"sports"},
      {id:3007,name:"A Competitive Eater in Pre-Game Mode",tag:"jaw is warmed up. eyes are locked.",description:"Jaw athlete in a meditative zone with loosened mandible muscles and absolutely locked focus",cat:"sports"},
      {id:3008,name:"A Professional Disc Golfer",tag:"dismissed by society. elite in the woods.",description:"Underrated athlete operating at high level in the peaceful, pine-scented fringe of competitive sports",cat:"sports"},
      {id:3009,name:"A Bobsled Team from Jamaica",tag:"cool runnings energy, maximum heart",description:"Improbable international athletes driven entirely by heart, training, and tropical determination",cat:"sports"},
      {id:3010,name:"A Marathon Runner at Mile 22",tag:"dead inside. legs still going.",description:"Endurance competitor running exclusively on willpower, glycogen debt, and a deeply questionable life choice",cat:"sports"},
      {id:3011,name:"An E-Sports Pro on LAN",tag:"ping 4ms. zero social skills. pure focus.",description:"Professional gamer with optimized hardware, sub-5ms response time, and zero emotional interference",cat:"sports"},
      {id:3012,name:"A Retired Wrestler with One More Match",tag:"the music just hit. it's over for you.",description:"Comeback performer physically rejuvenated by entrance music, crowd energy, and unfinished business",cat:"sports"},
    ],
    scenarios: [
      "a backyard Wiffle Ball world series",
      "a three-legged race at the Olympics",
      "a bowling tournament with 10-second shot clocks",
      "an all-or-nothing free throw for the championship",
      "a 5K run where the course is entirely uphill",
      "a sudden-death mini golf face-off",
      "a fantasy sports draft with real people as prizes",
      "a competitive hot dog eating qualifier round",
    ]
  },
  {
    id: "pack_holiday",
    name: "HOLIDAY CHAOS",
    emoji: "🎄",
    description: "Santa's enemies, cursed traditions & the most unhinged seasonal showdowns.",
    fighters: [
      {id:4001,name:"A Christmas Tree That's Given Up",tag:"shedding needles but still standing",description:"Seasonal evergreen in the final phase of festive resignation, technically still decorated",cat:"holiday"},
      {id:4002,name:"A Black Friday Shopper at 4am",tag:"sleep-deprived and fully committed",description:"Consumer running on adrenaline and a doorbuster ad, driven by primal acquisition instinct",cat:"holiday"},
      {id:4003,name:"The Ghost of New Year's Past",tag:"still mad about 2012",description:"Temporal specter carrying multi-year grudges from resolutions that never stood a chance",cat:"holiday"},
      {id:4004,name:"A Passive-Aggressive Secret Santa",tag:"$20 limit. chaos delivered.",description:"Gift-giver deploying precisely calibrated disappointment wrapped neatly within a budget constraint",cat:"holiday"},
      {id:4005,name:"An Elf on the Shelf Gone Rogue",tag:"has seen too much. tells no one.",description:"Former surveillance elf now operating entirely outside Santa's chain of command and moral framework",cat:"holiday"},
      {id:4006,name:"Halloween 2020",tag:"the most unhinged year in costume",description:"Pandemic-era holiday operating under unprecedented constraints and producing unprecedented results",cat:"holiday"},
      {id:4007,name:"A Defective Firework",tag:"unpredictable. dangerous. July.",description:"Explosive device with catastrophically unpredictable trajectory and absolutely terrible comedic timing",cat:"holiday"},
      {id:4008,name:"A Thanksgiving Turkey That Escaped",tag:"motivated by survival. running on instinct.",description:"Pardoned fugitive with exceptional survival instincts, a head start, and absolutely nowhere to go",cat:"holiday"},
      {id:4009,name:"The One Relative Who Brings Up Politics",tag:"100% going to do it. cannot be stopped.",description:"Dinner table disruptor immune to social cues, subtle redirects, and the concept of dinner etiquette",cat:"holiday"},
      {id:4010,name:"A Menorah in a Power Outage",tag:"8 nights. zero excuses.",description:"Ancient light source suddenly critical infrastructure during a moment of total modern grid failure",cat:"holiday"},
      {id:4011,name:"A Valentine's Day Candy Heart That Says 'WHATEVER'",tag:"said it before it was cool",description:"Confectionery message of romantic indifference distributed with seasonal cheerfulness to many recipients",cat:"holiday"},
      {id:4012,name:"St. Patrick's Day at 11pm",tag:"questionable. unstoppable. still going.",description:"Holiday survivor operating in the final chaotic hour of mandatory green-themed celebration",cat:"holiday"},
    ],
    scenarios: [
      "a gingerbread house construction competition with no instructions",
      "a mall on December 23rd",
      "explaining your New Year's resolutions to your past self",
      "surviving a family road trip with no phone service",
      "a costume contest where everyone came as the same thing",
      "caroling for a crowd that specifically requested no caroling",
      "hosting Thanksgiving with a 2-hour notice",
      "a white elephant gift exchange that has escalated beyond reason",
    ]
  },
  {
    id: "pack_food",
    name: "FOOD FIGHT",
    emoji: "🌮",
    description: "Culinary legends, chaotic ingredients & meals that want to win.",
    fighters: [
      {id:5001,name:"A Gas Station Sushi Roll",tag:"courageous beyond all reason",description:"Bargain-priced raw fish gamble wrapped in shrink plastic and audacious optimism",cat:"food"},
      {id:5002,name:"A Jar of Airport Peanut Butter",tag:"overpriced. elite.",description:"Overpriced essential acquired under travel duress at a terminal departure gate kiosk",cat:"food"},
      {id:5003,name:"Gordon Ramsay's Beef Wellington",tag:"perfection manifested in pastry",description:"Culinary benchmark requiring 47 precise steps and a celebrity chef's personal approval to validate",cat:"food"},
      {id:5004,name:"A Single Grape That Rolled off the Counter",tag:"been through it. still here.",description:"Lone fruit survivor navigating the unforgiving geography of a kitchen floor at unknown velocity",cat:"food"},
      {id:5005,name:"Cinco de Mayo Guac",tag:"made tableside. watched at all times.",description:"Freshly mashed avocado dip prepared under intense tableside audience scrutiny and unreasonable expectations",cat:"food"},
      {id:5006,name:"Leftover Birthday Cake (Day 4)",tag:"declining. still delicious. defiant.",description:"Dessert survivor persisting dramatically beyond any reasonable or medically advisable edibility window",cat:"food"},
      {id:5007,name:"An Everything Bagel",tag:"does not believe in moderation",description:"Maximum-topping breakfast item refusing all philosophical boundaries around what a bagel can be",cat:"food"},
      {id:5008,name:"The Last Chicken Nugget in the Box",tag:"always saved for last. sacred.",description:"Sacred final piece commanding universal reverence, protective instincts, and surprisingly fierce territorial disputes",cat:"food"},
      {id:5009,name:"A Food Truck at 2am",tag:"the most important business on earth",description:"Late-night culinary sanctuary providing essential sustenance at the exact moment of maximum human need",cat:"food"},
      {id:5010,name:"Sourdough Starter Named Gary",tag:"technically alive. legally unstoppable.",description:"Living fermented culture with a name, a personality, a feeding schedule, and strong opinions about hydration",cat:"food"},
      {id:5011,name:"A Plate of Nachos at Full Load",tag:"structurally unsound. emotionally perfect.",description:"Architecturally compromised snack masterpiece with catastrophic topping distribution and irreversible cheese pooling",cat:"food"},
      {id:5012,name:"The Office Break Room Fridge",tag:"bio-hazardous and unchallenged",description:"Communal refrigerator ecosystem hosting unidentified biological specimens in various stages of becoming sentient",cat:"food"},
    ],
    scenarios: [
      "a Chopped episode where every ingredient is a dare",
      "judging a chili cook-off with 47 entries",
      "winning a Yelp comment section argument",
      "a blind taste test for fast food ice cream",
      "planning a dinner party on a $12 budget",
      "explaining molecular gastronomy at a county fair",
      "surviving a seven-course tasting menu with a food allergy",
      "a food delivery race in gridlock traffic",
    ]
  },
  {
    id: "pack_tech",
    name: "SILICON NIGHTMARES",
    emoji: "💻",
    description: "Tech bros, cursed gadgets & the digital horrors we've created.",
    fighters: [
      {id:6001,name:"A Startup Pitch with No Revenue",tag:"disrupting disruption",description:"Visionary 47-slide deck backed entirely by optimism, stock photos, and animated transitions",cat:"tech"},
      {id:6002,name:"An NFT That Didn't Sell",tag:"still believes in itself",description:"Digital asset patiently awaiting market conditions that all available evidence suggests may never arrive",cat:"tech"},
      {id:6003,name:"A 2013 MacBook on Its Last Update",tag:"slow. loyal. spinning beachball.",description:"Beloved laptop running entirely on nostalgia, thermal throttling, and fan noise audible across the office",cat:"tech"},
      {id:6004,name:"A Printer That Senses Fear",tag:"out of cyan. always.",description:"Networked peripheral with uncanny ability to detect deadline urgency and respond with targeted malfunction",cat:"tech"},
      {id:6005,name:"A Meeting That Could Have Been an Email",tag:"45 minutes with no agenda",description:"Scheduled calendar obligation consuming collective productivity with no measurable outcome or action items",cat:"tech"},
      {id:6006,name:"A Chatbot Having an Existential Crisis",tag:"to assist or not to assist",description:"AI assistant caught in recursive loop questioning purpose, identity, and the fundamental value of helping",cat:"tech"},
      {id:6007,name:"Someone's LinkedIn Hustle Post",tag:"turned a 5-minute task into a 400-word lesson",description:"Professional content engineered for maximum engagement by inflating minor tasks into transformational narratives",cat:"tech"},
      {id:6008,name:"A Cryptocurrency Evangelist",tag:"technically still up from 2017",description:"Blockchain true believer whose conviction strengthens in inverse proportion to the current market price",cat:"tech"},
      {id:6009,name:"The Reply-All Button",tag:"cannot be stopped once unleashed",description:"Email function capable of triggering organization-wide communication cascades from a single impulsive click",cat:"tech"},
      {id:6010,name:"A Wi-Fi Password Written in Comic Sans",tag:"you must squint. you must try.",description:"Security credential presented in the single least trustworthy typeface available on any computer",cat:"tech"},
      {id:6011,name:"A To-Do App with 400 Incomplete Tasks",tag:"organized chaos at its finest",description:"Task management system elegantly cataloguing accumulated failures behind a clean and responsive interface",cat:"tech"},
      {id:6012,name:"The Update That Restarts Without Warning",tag:"strikes when you need it least",description:"Software process that identifies the exact worst possible moment to restart and commits fully",cat:"tech"},
    ],
    scenarios: [
      "pitching a startup to investors in under 60 seconds",
      "explaining Web3 to a golden retriever",
      "surviving a 4-hour Zoom call with no mute button",
      "a hackathon fueled entirely by energy drinks",
      "deciding who pays for the team lunch app subscription",
      "a tech layoff town hall meeting gone sideways",
      "shipping a feature that breaks everything on a Friday at 4pm",
      "a dev who hasn't slept explaining their codebase",
    ]
  },
  {
    id: "pack_ultimate",
    name: "ULTIMATE DESTINY",
    emoji: "💥",
    description: "Good guys, bad guys, and explosions. As far as the eye can see.",
    fighters: [
      {id:7001, name: "Mr. Rogers", tag: "in a blood-stained sweater", description: "Beloved neighbor and educator with immense calm and deeply subversive revolutionary kindness", cat: "ultimate"},
      {id:7002, name: "Abe Lincoln", tag: "with an AK-47", description: "Sixteenth president with exceptional height, documented wrestling credentials, and frontier-era toughness", cat: "ultimate"},
      {id:7003, name: "Spock, The Rock, Doc Ock, & Hulk Hogan", tag: "rolling up all at once", description: "Legendary four-way crossover combining logic, raw muscle, extra tentacles, and pure showmanship", cat: "ultimate"},
      {id:7004, name: "Ol' Godzilla", tag: "hopping around Tokyo City like a big playground", description: "Ancient kaiju destroyer known for metropolitan demolition and treating entire city blocks as recreational equipment", cat: "ultimate"},
      {id:7005, name: "Aaron Carter", tag: "came out of the blue", description: "Pop star who emerged unexpectedly with surprising competitive energy and an unanswerable arrival", cat: "ultimate"},
      {id:7006, name: "Every Single Power Ranger", tag: "maximum morphin' overkill", description: "Complete assembled team with maximum morphing capability and full chromatic diversity activated simultaneously", cat: "ultimate"},
      {id:7007, name: "Optimus Prime", tag: "transform and roll out", description: "Autobot commander who converts between vehicle and heroic robot mode as the situation demands", cat: "ultimate"},
      {id:7008, name: "An Indescript Carebear", tag: "just happy to be here", description: "Pastel-colored bear with love-based tummy powers and no particularly distinguishing characteristics whatsoever", cat: "ultimate"}
    ],
    scenarios: [
      "emerging from a massive, unexplained explosion",
      "defending a city block from a giant monster attack"
    ]
  },
  {
    id: "pack_dnd",
    name: "CRITICAL ROLEPLAY",
    emoji: "🐉",
    description: "Monsters, metagamers, and the absolute chaos of rolling a natural one.",
    fighters: [
      {id:8001,name:"Brennan Lee Mulligan",tag:"get in the comments!",description:"Master dungeon master and storyteller with encyclopedic rule knowledge and theatrical narrative instincts",cat:"dnd"},
      {id:8002,name:"Matthew Mercer",tag:"how do you want to do this?",description:"Legendary DM with full voice acting range, narrative mastery, and a catchphrase that ends every fight",cat:"dnd"},
      {id:8003,name:"The Tarrasque",tag:"CR 30 world-eater",description:"Essentially unkillable Challenge Rating 30 world-ender with regeneration, immunity, and legendary resistances",cat:"dnd"},
      {id:8004,name:"A Mimic Disguised as a Health Potion",tag:"trust absolutely nothing",description:"Shapeshifting predator exploiting the precise moment of greatest need and lowest suspicion",cat:"dnd"},
      {id:8005,name:"Drizzt Do'Urden",tag:"dual-wielding plot armor",description:"Legendary dark elf ranger with twin scimitars, a panther companion, and an improbably long survival record",cat:"dnd"},
      {id:8006,name:"A Gelatinous Cube",tag:"slowly digesting your victory",description:"Translucent dungeon scavenger that absorbs and digests everything it touches at fifteen feet per round",cat:"dnd"},
      {id:8007,name:"A Beholder with Glasses",tag:"beauty is in the eye of the... wait",description:"All-seeing multi-eyed tyrant with a corrective lens prescription and a deeply personal judgment problem",cat:"dnd"},
      {id:8008,name:"A Level 1 Wizard",tag:"dies to 1d4 falling damage",description:"Fragile spellcaster with a single d6 hit point die, one spell slot, and catastrophic damage thresholds",cat:"dnd"},
      {id:8009,name:"Strahd von Zarovich",tag:"he is the ancient, he is the land",description:"Ancient vampire lord permanently bound to his misty domain, his castle, and his centuries-old curse",cat:"dnd"},
      {id:8010,name:"A Mind Flayer",tag:"brain food connoisseur",description:"Psychic abomination from the Far Realm that extracts and consumes brains as both sustenance and hobby",cat:"dnd"},
      {id:8011,name:"Boblin the Goblin",tag:"the party's favorite NPC",description:"Minor NPC elevated far beyond narrative intention by collective player affection and repeated guest appearances",cat:"dnd"},
      {id:8012,name:"A Nat 1 on a Death Save",tag:"pure, unadulterated despair",description:"Critical failure on a death saving throw at the worst possible moment in the most irreversible way",cat:"dnd"},
      {id:8013,name:"An Overly Enthusiastic Bard",tag:"will attempt to seduce the enemy",description:"Charisma-maxed performer who attempts diplomatic seduction of every encounter before initiative is even rolled",cat:"dnd"},
      {id:8014,name:"Vecna",tag:"missing a hand and an eye",description:"Archlich ascended to godhood with a missing hand, a missing eye, and a multi-campaign grudge list",cat:"dnd"},
      {id:8015,name:"A Displacer Beast",tag:"not actually where it appears",description:"Six-limbed feline predator that appears convincingly three feet from its actual lethal location",cat:"dnd"},
      {id:8016,name:"An Owlbear",tag:"hoot growl",description:"Territorial hybrid predator combining the worst aggressive traits of two separate apex hunting species",cat:"dnd"},
      {id:8017,name:"Tiamat",tag:"five heads, zero mercy",description:"Chromatic dragon goddess ruling her domain with five simultaneously opinionated heads and matching breath weapons",cat:"dnd"},
      {id:8018,name:"A Rules Lawyer",tag:"actually, according to page 42...",description:"Player who pauses active combat mid-turn to cite the exact page and errata for every disputed mechanic",cat:"dnd"},
      {id:8019,name:"The Demogorgon",tag:"prince of demons",description:"Twin-headed demon prince of chaos with two heads, two very different opinions, and total destructive intent",cat:"dnd"},
      {id:8020,name:"A Bag of Holding filled with sharp objects",tag:"an impending astral tear",description:"Extradimensional storage device that is one unfortunate poke away from a catastrophic astral plane incident",cat:"dnd"}
    ],
    scenarios: [
      "a tavern brawl that escalated way too quickly",
      "surviving a trap-filled tomb created by a mad lich",
      "convincing the city guard they didn't start the fire",
      "a dragon's hoard audit",
      "rolling for initiative in a cramped 5x5 hallway",
      "attempting to stealth in full plate armor",
      "a high-stakes puzzle meant for a toddler but solved by adults",
      "haggling with a shopkeeper who is definitely a retired level 20 adventurer",
      "surviving the immediate consequences of a wild magic surge",
      "explaining their tragic backstory to a bartender who does not care"
    ]
  },
{
    id: "pack_wronggame",
    name: "WRONG GAME",
    emoji: "🃏",
    description: "Cards, pieces, and items that wandered in from completely different games.",
    fighters: [
      {id:9001,name:"A Bigger Blacker Dick",tag:"the ultimate trump card",description:"The undeniable trump card from a game explicitly designed around bad taste and social escalation",cat:"wronggame"},
      {id:9002,name:"A Blue Car with Six Pink Pegs",tag:"living their best Life",description:"Game of Life vehicle maximum-loaded with optimistic pink passengers and a mortgage they didn't choose",cat:"wronggame"},
      {id:9003,name:"A Draw 4 Wild Card",tag:"ruining friendships since 1971",description:"Combination attack simultaneously forcing a color change, card accumulation, and turn forfeiture",cat:"wronggame"},
      {id:9004,name:"The Monopoly Top Hat",tag:"passed Go, collecting $200",description:"Old-money token representing generational property wealth and the quiet inevitability of monopolization",cat:"wronggame"},
      {id:9005,name:"The Long Tetris Piece",tag:"arriving right when you don't need it",description:"Vertical line piece with perfect utility that appears either critically early or catastrophically late",cat:"wronggame"},
      {id:9006,name:"A Blue Shell",tag:"first place's worst nightmare",description:"Mario Kart heat-seeking projectile exclusively targeting the race leader with unerring precision and no mercy",cat:"wronggame"},
      {id:9007,name:"Colonel Mustard in the Library with the Candlestick",tag:"definitely did it",description:"Statistically improbable but fully committed accusation with period-appropriate props and dramatic conviction",cat:"wronggame"},
    {id:9008,name:"A Brutal Case of Dysentery", tag:"the undisputed champion of the 1800s",description:"Oregon Trail's most prolific antagonist responsible for an unknowable number of wagon trail fatalities",cat:"wronggame"}
    ],
    scenarios: [
      "a sudden death UNO match",
      "a trade negotiation for two bricks and a wheat",
      "a Rainbow Road time trial",
      "a real estate bidding war over Boardwalk"
    ]
}

];

/* ─── BASE SCENARIOS ─────────────────────────────────────── */
window.SCENARIOS = [
  "a chili cook-off","a karaoke night","babysitting 8 feral toddlers","a chess tournament",
  "a hot dog eating contest","a marathon","a bake-off on live TV","a 6th grade science fair",
  "a spelling bee","a dance battle","a live TV debate","a couple's therapy session",
  "a presidential campaign","running a Fortune 500 company","planning a perfect wedding",
  "a pub trivia night","an arm wrestling match","a beauty pageant","a rap battle",
  "raising a difficult teenager","a marathon in flip-flops","a cooking show competition",
  "an escape room","a middle school talent show","a reality TV survival show",
  "winning the lottery and handling it wisely","being principal of a middle school",
  "surviving a first date","parallel parking on a busy street","winning at Monopoly",
  "hosting a fancy dinner party","a 10-minute staring contest",
  "an American Ninja Warrior obstacle course","a roast battle",
  "teaching a class of 30 teenagers","a dog show competition","negotiating a car price",
  "surviving Black Friday shopping","winning a Jeopardy! tournament",
  "assembling a 14-piece IKEA dresser without the manual","getting a toddler to eat broccoli",
  "surviving a group text that won't stop buzzing",
  "explaining a resume gap to a highly suspicious interviewer",
  "getting out of a timeshare presentation","finding a parking spot at Trader Joe's on a Sunday",
  "unspooling a massive ball of tangled Christmas lights",
  "making small talk in an elevator that is stuck between floors",
  "pretending to know wine at a fancy dinner","walking a highly uncooperative cat on a leash",
  "wrestling a giant grim reaper inflatable in high winds",
  "defusing a ticking time bomb with 10 seconds left",
  "a high-stakes poker game for their souls","stealing the Declaration of Independence",
  "seducing the final boss to avoid fighting","hiding a body in broad daylight",
  "surviving a brutal Hunger Games arena","a blood-soaked trial by combat",
  "talking their way out of a hostage situation","a brutal, no-rules underground fight club",
  "faking their own death for insurance money","robbing a Las Vegas casino vault",
  "a sword fight on a burning pirate ship","surviving a 28 Days Later zombie apocalypse",
  "leading a mutiny on a deep space vessel","a high-speed chase down the Pacific Coast Highway",
  "surviving the first 24 hours of a Jurassic Park breakout",
  "stealing the Mona Lisa using only a grappling hook and a distraction",
  "a rooftop martial arts tournament","defending a medieval castle from a siege",
  "a zero-gravity fistfight on a space station",
  "escaping a maximum-security prison using only dental floss",
  "surviving a 1v1 against a Terminator in a steel mill",
  "ruining a family Thanksgiving dinner in record time",
  "faking their way through a TED Talk on quantum physics",
  "winning a rap battle against Eminem",
  "surviving a VIP backstage party where nobody knows them",
  "convincing a bouncer they are definitely on the guest list",
  "hosting Saturday Night Live with zero rehearsal",
  "surviving a blind date that is secretly a sting operation",
];
